require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - '.internal_test_app/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/internal/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.2
  DisplayCopNames: true

Rails:
  Enabled: true

# Metrics/LineLength:
#   Max: 120

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Exclude:
  - 'spec/**/*'

Style/DoubleNegation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

# Temp. disable due to https://github.com/bbatsov/rubocop/issues/3514
Style/VariableNumber:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/views/**/*'

Metrics/AbcSize:
  Max: 20

Metrics/ModuleLength:
  Max: 120

Metrics/LineLength:
  Max: 160

Metrics/ClassLength:
  Exclude:
    - 'app/models/spotlight/resource.rb'
    - 'lib/generators/spotlight/**/*' # Generators tend to have longer class lengths due to their lengthy public API

Style/PredicateName:
  Exclude:
    - 'app/models/concerns/spotlight/ar_light.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/generators/spotlight/**/*'

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Max: 8
  Exclude:
    - 'spec/features/**/*'

Bundler/DuplicatedGem:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
