require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - '.internal_test_app/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/internal/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Rails:
  Enabled: true

# Metrics/LineLength:
#   Max: 120

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Exclude:
  - 'spec/**/*'

Style/DoubleNegation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/views/**/*'

Metrics/AbcSize:
  Max: 20

Metrics/ModuleLength:
  Max: 120
  Exclude:
    - 'spec/fixtures/**/*'

Metrics/LineLength:
  Max: 160

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - blacklight-spotlight.gemspec
    - config/**/*
    - 'lib/tasks/*'
    - 'spec/**/*'
    - 'app/models/spotlight/blacklight_configuration.rb'
    - 'app/models/spotlight/resource.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/models/spotlight/resource.rb'
    - 'app/models/spotlight/resources/iiif_manifest.rb'
    - 'lib/generators/spotlight/**/*' # Generators tend to have longer class lengths due to their lengthy public API

Naming/PredicateName:
  Exclude:
    - 'app/models/concerns/spotlight/ar_light.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/generators/spotlight/**/*'
    - 'spec/fixtures/**/*'

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Max: 9
  Exclude:
    - 'spec/features/**/*'

Bundler/DuplicatedGem:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/ApplicationJob:
  Enabled: false

Rails/InverseOf:
  Enabled: false
