inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  Exclude:
    - '.internal_test_app/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/internal/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.5
  DisplayCopNames: true

Bundler/DuplicatedGem:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Capybara/VisibilityMatcher:
  Enabled: false

Layout/LineLength:
  Max: 160

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'app/controllers/spotlight/home_pages_controller.rb'
    - 'app/services/spotlight/exhibit_import_export_service.rb'

Metrics/ModuleLength:
  Max: 120
  Exclude:
    - 'spec/fixtures/**/*'

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - blacklight-spotlight.gemspec
    - config/**/*
    - 'lib/tasks/*'
    - 'spec/**/*'
    - 'app/models/spotlight/blacklight_configuration.rb'
    - 'app/models/spotlight/resource.rb'

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'app/models/spotlight/resources/iiif_manifest.rb'
    - 'app/services/spotlight/exhibit_import_export_service.rb'
    - 'lib/generators/spotlight/**/*' # Generators tend to have longer class lengths due to their lengthy public API

Naming/PredicateName:
  Exclude:
    - 'app/models/concerns/spotlight/ar_light.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/spotlight/home_pages_controller.rb'
    - 'app/services/spotlight/exhibit_import_export_service.rb'
    - 'lib/generators/spotlight/**/*'
    - 'spec/fixtures/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/spotlight/home_pages_controller.rb'
    - 'app/services/spotlight/exhibit_import_export_service.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/controllers/spotlight/home_pages_controller.rb'
    - 'app/services/spotlight/exhibit_import_export_service.rb'

Rails:
  Enabled: true

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/i18n_spec.rb'

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Max: 9
  Exclude:
    - 'spec/features/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Exclude:
  - 'spec/**/*'

Style/DoubleNegation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false
