services:
  solr:
    environment:
      - SOLR_PORT # Set via environment variable or use default defined in .env file
      - SOLR_VERSION # Set via environment variable or use default defined in .env file
      - SOLR_MODULES # Set via environment variable or use default defined in .env file
    image: "solr:${SOLR_VERSION}"
    volumes:
      - $PWD/lib/generators/spotlight/templates/solr/conf:/opt/solr/conf
    ports:
      - "${SOLR_PORT}:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - blacklight-core
      - /opt/solr/conf
