services:
  web:
    build:
      context: .
    image: spotlight
    stdin_open: true
    tty: true
    restart: always
    env_file:
      - .env
    volumes:
      - .:/spotlight/engine
      - spotlight_app:/spotlight/app
    ports:
      - 3000:3000
    depends_on:
      - db_migrate
      - solr
    networks:
      - spotlight

  db_migrate:
    image: spotlight
    env_file:
      - .env
    environment:
      SKIP_TRANSLATION: "yes"
    entrypoint: sh -c '/spotlight/engine/bin/db-migrate-seed.sh'
    volumes:
      - .:/spotlight/engine
      - spotlight_app:/spotlight/app
    networks:
      - spotlight

  solr:
    environment:
      - SOLR_PORT # Set via environment variable or use default defined in .env file
      - SOLR_VERSION # Set via environment variable or use default defined in .env file
      - SOLR_MODULES # Set via environment variable or use default defined in .env file
    image: "solr:${SOLR_VERSION}"
    volumes:
      - $PWD/lib/generators/spotlight/templates/solr/conf:/opt/solr/conf
    ports:
      - "${SOLR_PORT}:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - blacklight-core
      - /opt/solr/conf
    networks:
      - spotlight

volumes:
  spotlight_app:

networks:
  spotlight:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-spotlight
