require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

module Spotlight
  describe PagesController do
    routes { Spotlight::Engine.routes }

    # This should return the minimal set of attributes required to create a valid
    # Page. As you add validations to Page, be sure to
    # adjust the attributes here as well.
    let(:valid_attributes) { { "title" => "MyString" } }
    describe "when signed in as a curator" do
      let(:user) { FactoryGirl.create(:exhibit_curator) }
      before {sign_in user }

      describe "GET index" do
        let!(:page) { FactoryGirl.create(:page) }
        it "assigns all pages as @pages" do
          get :index, exhibit_id: Spotlight::Exhibit.default
          expect(assigns(:pages)).to include page
          expect(assigns(:exhibit)).to eq Spotlight::Exhibit.default
        end
      end

      describe "GET show" do
        let(:page) { FactoryGirl.create(:page) }
        it "assigns the requested page as @page" do
          get :show, id: page
          assigns(:page).should eq(page)
        end
      end

      describe "GET new" do
        it "assigns a new page as @page" do
          get :new, exhibit_id: Spotlight::Exhibit.default
          expect(assigns(:page)).to be_a_new(Page)
          expect(assigns(:page).exhibit).to eq Spotlight::Exhibit.default
        end
      end

      describe "GET edit" do
        let(:page) { FactoryGirl.create(:page) }
        it "assigns the requested page as @page" do
          get :edit, {:id => page}
          expect(assigns(:page)).to eq page
        end
      end

      describe "POST create" do
        describe "with valid params" do
          it "creates a new Page" do
            expect {
              post :create, page: {title: "MyString"} , exhibit_id: Spotlight::Exhibit.default
            }.to change(Page, :count).by(1)
          end

          it "assigns a newly created page as @page" do
            post :create, page: {title: "MyString"}, exhibit_id: Spotlight::Exhibit.default
            assigns(:page).should be_a(Page)
            assigns(:page).should be_persisted
          end

          it "redirects to the created page" do
            post :create, page: {title: "MyString"}, exhibit_id: Spotlight::Exhibit.default
            response.should redirect_to(Page.last)
          end
        end

        describe "with invalid params" do
          it "assigns a newly created but unsaved page as @page" do
            # Trigger the behavior that occurs when invalid params are submitted
            Page.any_instance.stub(:save).and_return(false)
            post :create, page: { "title" => "invalid value" }, exhibit_id: Spotlight::Exhibit.default
            assigns(:page).should be_a_new(Page)
          end

          it "re-renders the 'new' template" do
            # Trigger the behavior that occurs when invalid params are submitted
            Page.any_instance.stub(:save).and_return(false)
            post :create, page: { "title" => "invalid value" }, exhibit_id: Spotlight::Exhibit.default
            response.should render_template("new")
          end
        end
      end

      describe "PUT update" do
        let(:page) { FactoryGirl.create(:page) }
        describe "with valid params" do
          it "updates the requested page" do
            # Assuming there are no other pages in the database, this
            # specifies that the Page created on the previous line
            # receives the :update_attributes message with whatever params are
            # submitted in the request.
            Page.any_instance.should_receive(:update).with(valid_attributes)
            put :update, {:id => page, :page => valid_attributes}
          end

          it "assigns the requested page as @page" do
            put :update, {:id => page, :page => valid_attributes}
            assigns(:page).should eq(page)
          end

          it "redirects to the page" do
            put :update, {:id => page, :page => valid_attributes}
            response.should redirect_to(page)
          end
        end

        describe "with invalid params" do
          it "assigns the page as @page" do
            # Trigger the behavior that occurs when invalid params are submitted
            Page.any_instance.stub(:save).and_return(false)
            put :update, {:id => page, :page => { "title" => "invalid value" }}
            assigns(:page).should eq(page)
          end

          it "re-renders the 'edit' template" do
            # Trigger the behavior that occurs when invalid params are submitted
            Page.any_instance.stub(:save).and_return(false)
            put :update, {:id => page, :page => { "title" => "invalid value" }}
            response.should render_template("edit")
          end
        end
      end

      describe "DELETE destroy" do
        let!(:page) { FactoryGirl.create(:page) }
        it "destroys the requested page" do
          expect {
            delete :destroy, {:id => page}
          }.to change(Page, :count).by(-1)
        end

        it "redirects to the pages list" do
          delete :destroy, {:id => page}
          response.should redirect_to(exhibit_pages_url(Spotlight::Exhibit.default))
        end
      end
    end
  end
end
